### ISSUE TITLE
E2 shared-core instances network information missing

### ISSUE THREAD

**Issue by gdubicki** [doitintl/gcpinstances.info#19]
Hi!

GCP docs provide info about E2 shared-core (e2-micro, e2-small, e2-medium) network badwidth limits, see https://cloud.google.com/compute/docs/general-purpose-machines#e2_machine_types but your app shows that is is "Unknown".

Is it a bug/missing feature or is there a reason for that?

**Comment by Burekasim** [comment]
Hi @gdubicki , 

Thanks for bringing this to my attention, 
Because this data was scraped manually, it's not updated automatically, 
I've [updated the data](https://github.com/doitintl/gcpinstances.info/pull/21/commits/0bf87e44f9cdb18a0505058f75eedd1941e0c646) and it's now available on the website. 

Thanks a lot :)

**Comment by gdubicki** [comment]
Thanks for a quick fix @Burekasim ! 😊
